name: MediRate
description: Meditate based off your heart rate

version: 1.0.1+2

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  charts_flutter: ^0.9.0
  wakelock: ^0.1.4+1
  provider:
  flutter_better_camera: ^0.6.1
  # camera:
  #   git:
  #     url: https://github.com/Renesanse/plugins.git
  #     path: packages/camera
  #     ref: flash_light
  fl_chart: ^0.11.1
  smart_signal_processing: ^2.1.1
  scidart: ^0.0.1-dev.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.3

flutter_icons:
  android: "launcher_icon" 
  ios: true
  image_path: "assets/icon.png"



flutter:
  uses-material-design: true
  assets:
    - assets/sprites.png
    - assets/sprite_in_motion.png